version: '3.4'

services:

  webspa:
    image: ${DOCKER_REGISTRY-}demowebspa 
    build:
      context: ./web/
      dockerfile: ./Demo.WebSpa/Dockerfile
    container_name: webspa
    depends_on:
      - apigw

  apigw:
    image: ${DOCKER_REGISTRY-}apigw
    build:
      context: ./apigateways/
      dockerfile: ./Demo.ApiGateWay/Dockerfile
    container_name: apigw
    depends_on:
    - demo.applicants.api
    - demo.identity.api
    - demo.jobs.api

  demo.applicants.api:
    image: ${DOCKER_REGISTRY-}demoapplicantsapi
    build:
      context: ./services/
      dockerfile: ./Demo.Applicants.Api/Dockerfile
    container_name: applicants.api

  demo.identity.api:
    image: ${DOCKER_REGISTRY-}demoidentityapi
    build:
      context: ./services/
      dockerfile: ./Demo.Identity.Api/Dockerfile
    environment:
      - RedisHost=user.data:6379
    container_name: identity.api

  demo.jobs.api:
    image: ${DOCKER_REGISTRY-}demojobsapi
    build:
      context: ./services/
      dockerfile: ./Demo.Jobs.Api/Dockerfile
    container_name: jobs.api
    depends_on:
      - sql.data

  sql.data:
   image: mssql-linux
   build:
     context: .
     dockerfile: ./database/Dockerfile
   container_name: mssql-linux
  
  user.data:
    image: redis
    container_name: user.data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq