version: '3.4'

services:

  webspa:
    image: ${DOCKER_REGISTRY-}demowebspa 
    build:
      context: ./web/
      dockerfile: ./Demo.WebSpa/Dockerfile
    ports: 
    - "8080:80"
    container_name: webspa
    depends_on:
      - demo.applicants.api
      - demo.identity.api
      - demo.jobs.api

  demo.applicants.api:
    image: ${DOCKER_REGISTRY-}demoapplicantsapi
    build:
      context: ./services/
      dockerfile: ./Demo.Applicants.Api/Dockerfile
    ports: 
    - "8081:80"
    container_name: applicants.api

  demo.identity.api:
    image: ${DOCKER_REGISTRY-}demoidentityapi
    build:
      context: ./services/
      dockerfile: ./Demo.Identity.Api/Dockerfile
    ports: 
    - "8084:80"
    environment:
      - RedisHost=user.data:6379
    container_name: identity.api

  demo.jobs.api:
    image: ${DOCKER_REGISTRY-}demojobsapi
    build:
      context: ./services/
      dockerfile: ./Demo.Jobs.Api/Dockerfile
    ports: 
    - "8083:80"
    container_name: jobs.api
    depends_on:
      - sql.data

  sql.data:
   image: mssql-linux
   build:
     context: .
     dockerfile: ./database/Dockerfile
   ports:
      - "5433:1433"
   container_name: mssql-linux
  
  user.data:
    image: redis
    container_name: user.data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
    container_name: rabbitmq